-run_mode=true
-log_file=/im/logs/user.log
-log_level=0
-registry_host=http://192.168.91.129:2379
-instance_name=/user_service/instance
-access_host=192.168.91.129:10003
-listen_port=10003
-rpc_timeout=-1
-rpc_threads=1
-base_service=/service
-file_service=/service/file_service
-es_host=http://192.168.91.129:9200/
-mysql_host=192.168.91.129
-mysql_user=root
-mysql_pswd=Hlb030509!
-mysql_db=chat_im
-mysql_cset=utf8
-mysql_port=0
-mysql_pool_count=4
-redis_host=192.168.91.129
-redis_port=6379
-redis_db=0
-redis_keep_alive=true
-dms_key_id=LTAI5t5i2W6bRj9N3oDhyT1y
-dms_key_secret=TZyxvFGOhNEsD4jWfQVYT46Z5okaT1